about: {home: www.econ.upf.edu/~shansen/, license: Hansen License}
build:
  entry_points: []
  features: []
  string: ''
  track_features: []
package: {name: samplers, version: 1.0.0}
requirements:
  build: [python, cython, numpy]
  conflicts: []
  run: [python, cython, numpy]
source:
  git_branch: ''
  git_tag: ''
  git_url: https://github.com/sekhansen/text-mining-tutorial.git
  md5: ''
  patches: []
  svn_rev: ''
test:
  commands: []
  files: []
  imports: []
  requires: [numpy, cython]
